cc_binary(
    name = "main",
    deps = [
        "//:simpledb",
        "@com_github_gflags_gflags//:gflags"
    ],
    srcs = glob(["src/**"]),
    visibility = ["//visibility:public"],
    linkstatic = True,
)
